# Build Stage will take base image only for required task (119 MB)
# Stage 1 (builder)
FROM python:3.14-slim AS builder

WORKDIR /app

# Copy dependency file first for efficient caching
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt --target=/app/library


# Copy all application source code
COPY . .

# Final Distroless Image Stage with even lesser size (63 MB)
# Stage 2 (deployer)
FROM gcr.io/distroless/python3-debian12 AS deployer

WORKDIR /app

# Copy dependencies from the builder stage
COPY --from=builder /app/library /app/library
COPY --from=builder /app .

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH="/app/library"

# Expose the application port
EXPOSE 80

# Run the application
CMD ["run.py"]

